name: xdnmb_api
description: API for nmbxd.com.
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  html: ^0.15.4
  http: ^1.2.1
  http_parser: ^4.0.2
  mime: ^1.0.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
