name: xdnmb_api
description: API for nmbxd.com.
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  html: ^0.15.2
  http: ^0.13.5
  http_parser: ^4.0.2
  mime: ^1.0.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
