name: xdnmb_api
description: API for nmbxd.com.
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  html: ^0.15.4
  http: ^1.1.0
  http_parser: ^4.0.2
  mime: ^1.0.4

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
